language: ruby
sudo: false
before_install:
  - gem install bundler
dist: trusty
rvm:
  - 2.4.0
script: bundle exec rake test
notifications:
  email: false
env:
  global:
    - secure: JtT9vwmixV5eZ9/bkCVbrUtXeBSDl4xgNKHnKCEVPhNMwEn4oPRPAk612dp4rxYj4mQJpNnGf8ARAd573AY34LIdIArW0JaFAvLOqjz3bEuLpf0SbYS7bfBi/YhUeSEluPmyZxkavrMJ18lTPbHqfn3vP95PCcGtdjm00M4jlWI=
    - secure: j0C//Zg8QMsNH3wuew19IVocOmkAcqid+Y4qEXppwaMJpRWP/bWa7vcur3647iTuX7STcqKuRKj4YtUE+f61ihxFuDqUFZnu4eqEHco98R7OiYxEgu8zQ0zSXlXFw2kvLHKnDJ/mV0iLUSGpAgQdFNjsLSgD/Lc/lCRInDYOpM0=
