language: ruby
sudo: false
before_install:
  - gem install bundler
  - gem update --system
dist: trusty
rvm:
  - 2.4
script: bundle exec rake test
notifications:
  email: false
env:
  global:
    - secure: "sCx6hjf1f/JuBSOCKkDXCPrM5CZehHs/Ibp9Z5vYX0ZjPSlWD9CKt/emupslD1axmImIjK/M99bvHlF3kAgTxhHKyHzvk63M7IcmTNStGbQj9WPTwHXLjwoKVa+gtMCW1XtlyfeyTC5HHAnEExduvw2x7f/am8/4qq2varOQbG8="
    - secure: "iEHH9GSm02uKhVy04ymms5ydFsww2UmBIFKJwxmEvND1mUzABqBf+v+emMP7XPSLs/L3v+XyAy08kWM4n132Ul/h/XTDeM3W15CRKCABxhPesxzoczki95eJ6E6hMF+4HlfTXSGLKtTb6R18fvtbq0pSJOL4SNpd7YsIe+VSnmY="
