language: ruby
sudo: false
before_install:
  - gem install bundler # the default bundler version on travis is very old and causes dependency issues
dist: trusty
rvm:
  - 2.4
script: bundle exec rake test
notifications:
  email: false
